### ISSUE TITLE
Errors occur at the beginning of preparing to merge the observations.

### ISSUE THREAD

**Issue by wanglei773778083** [bcalden/ClusterPyXT#15]
After downloading the cluster data from Chandra Data Archive , when it is doing preparing to merge the observations：

Reprocessing Abell 85
Reprocessing Abell 85/4881
Traceback (most recent call last):
  File "clusterpyxt.py", line 117, in <module>
    menu.make_menu()
  File "/home/wanglei/xray/ClusterPyXT-master/menu.py", line 301, in make_menu
    display_menu(main_menu)
  File "/home/wanglei/xray/ClusterPyXT-master/menu.py", line 198, in display_menu
    selected_action['function']()
  File "/home/wanglei/xray/ClusterPyXT-master/menu.py", line 171, in continue_cluster
    ciao.start_from_last(current_cluster)
  File "/home/wanglei/xray/ClusterPyXT-master/ciao.py", line 1085, in start_from_last
    success = function_steps[pypeline_progress_index](cluster)
  File "/home/wanglei/xray/ClusterPyXT-master/ciao.py", line 406, in merge_observations
    reprocess_cluster(cluster)
  File "/home/wanglei/xray/ClusterPyXT-master/ciao.py", line 230, in reprocess_cluster
    copy_event_files(observation.reprocessing_directory, observation.analysis_directory)
  File "/home/wanglei/xray/ClusterPyXT-master/ciao.py", line 278, in copy_event_files
    evt2_filename = evt2_filename[-1]
IndexError: list index out of range

ps ：Computer system is Linux Ubuntu 64 bit，ciao-4.11

**Comment by bcalden** [comment]
What observation id's are you using? Any other than 4881? I will try to recreate the error and get a fix out right away.

**Comment by wanglei773778083** [comment]
> What observation id's are you using? Any other than 4881? I will try to recreate the error and get a fix out right away.

I used 4881 4882 and 4883.

**Comment by bcalden** [comment]
In your directory, ../A85/4881/analysis/repro/ directory, do you have a file named something similar to acisf04881_repro_evt2.fits ?

I was able to run stage one with those three observations without issue and it appears the error you posted is the pipeline unable to find your reprocessed level to event file. Let me know if you have that file or not and I can further troubleshoot.

**Comment by wanglei773778083** [comment]
> In your directory, ../A85/4881/analysis/repro/ directory, do you have a file named something similar to acisf04881_repro_evt2.fits ?
> 
> I was able to run stage one with those three observations without issue and it appears the error you posted is the pipeline unable to find your reprocessed level 2 event file. Let me know if you have that file or not and I can further troubleshoot.

There is nothing in ../A85/4881/analysis/repro，i think chandra_repro didn't work.

**Comment by bcalden** [comment]
Did that fix it? I just updated the dev branch to add checking to make sure repro produces something. An error posts if not. 

If the directory naming was the issue, should I clarify something in specific to help ensure this problem doesn't happen again to someone else?

Also, thanks for posting the issue and helping try to work this out!

**Comment by wanglei773778083** [comment]
> Did that fix it? I just updated the dev branch to add checking to make sure repro produces something. An error posts if not.
> 
> If the directory naming was the issue, should I clarify something in specific to help ensure this problem doesn't happen again to someone else?
> 
> Also, thanks for posting the issue and helping try to work this out!



I think joining tips is helpful for beginners,especially for people like me who are not familiar with CIAO.

Thank you for all the work you've done, which has made the process of data processing easier.

**Comment by bcalden** [comment]
Thank you very much for your input! I am in the process of creating a guided walkthrough on how to process a cluster. Along the way I will add some of the "gotchas" or common quirks which may arise and how to deal with them. If any other issues arise, please post an issue and I will get on it ASAP.
