### ISSUE TITLE
Error: pget() Parameter not found

### ISSUE THREAD

**Issue by Sgilvan** [bcalden/ClusterPyXT#27]
I will be using CLusterPyXT (https://github.com/bcalden/ClusterPyXT/tree/dev-CIAO-4.12) to produce spectral maps for Chandra data in a Linux Ubuntu 18.04.5 machine.
To do so I had to install Ciao (version 4.12) using anaconda3 and Python 3.8.3.
The system downloads the observation data and then presents the following message:
********
The data have been reprocessed.
Start your analysis with the new products in
/home/user/Doutorado/A2199/10748/repro
Running ccd_sort on A2199.
Working on A2199/10748
evt1 : ['/home/user/Doutorado/A2199/10748/secondary/acisf10748_001N002_evt1.fits']
evt2 : /home/user/Doutorado/A2199/10748/repro/acisf10748_repro_evt2.fits
detname : ACIS-01236
A2199/10748: Making level 2 event file for ACIS Chip id: 0
A2199/10748: Making level 2 event file for ACIS Chip id: 1
A2199/10748: Making level 2 event file for ACIS Chip id: 2
A2199/10748: Making level 2 event file for ACIS Chip id: 3
A2199/10748: Making level 2 event file for ACIS Chip id: 6
Running ciao_back on A2199.
Finding background for /home/user/Doutorado/A2199/10748/analysis/acis_ccd2.fits
Found background at /home/user/anaconda3/envs/ciao-4.12/CALDB/data/chandra/acis/bkgrnd/acis2iD2009-09-21bkgrnd_ctiN0003.fits
pset: cannot convert parameter value : rval
/tmp/tmpamechstz.dmkeypar.par: cannot convert parameter value : rval
Error getting parameter file in CIAO. Please close ClusterPyXT and re-try the stage. If the problem persists, please file a bug report on https://github.com/bcalden/ClusterPyXT with the following error message:
Traceback (most recent call last):
File "clusterpyxt.py", line 496, in run_stage_1
ciao.run_stage_1(self._cluster_obj)
File "/home/user/ClusterPyXT-dev-CIAO-4.12/ciao.py", line 1313, in run_stage_1
merge_observations(cluster)
File "/home/user/ClusterPyXT-dev-CIAO-4.12/ciao.py", line 485, in merge_observations
ciao_back(cluster)
File "/home/user/ClusterPyXT-dev-CIAO-4.12/ciao.py", line 188, in ciao_back
echo=True)
File "/home/user/anaconda3/envs/ciao-4.12/lib/python3.5/site-packages/ciao_contrib/runtool.py", line 1810, in __call__
stackfiles = self._update_parfile(parfile)
File "/home/user/anaconda3/envs/ciao-4.12/lib/python3.5/site-packages/ciao_contrib/runtool.py", line 1365, in _update_parfile
self._update_parfile_verify(parfile, stackfiles)
File "/home/user/anaconda3/envs/ciao-4.12/lib/python3.5/site-packages/ciao_contrib/runtool.py", line 1294, in _update_parfile_verify
oval = _to_python(ptype, pio.pget(fp, oname))
ValueError: pget() Parameter not found
Abort (core dumped)

**********
Do you have any idea why this error?

**Comment by adrabent** [comment]
@Sgilvan 
I have exactly the same issue using also ciao-4.12 (installed with conda).
It seems to be an issue with `dmkeypar`, which uses an `rval` parameter.

https://cxc.cfa.harvard.edu/ciao/ahelp/dmkeypar.html

Alex

**Comment by gabriel-fontinele** [comment]
@Sgilvan @adrabent @bcalden 
Has anyone managed to resolve this issue? I'm going through it too.
