### ISSUE TITLE
CIAO4.14

### ISSUE THREAD

**Issue by Swarau** [bcalden/ClusterPyXT#33]
Dear sir,
Could I use it for CIAO version 4.14 ?

**Comment by bcalden** [comment]
It does work with CIAO 4.14. When you posted, the CIAO 4.14 compatability was a seperate branch but has since been updated to the master branch. That is a long way of saying the default ClusterPyXT you checkout from github should be compatible with CIAO-4.14.

**Comment by Swarau** [comment]
Thank you so much sir.
